p = input("Enter a place: ")
name = input("Enter a name: ")
a1 = input("Enter an adjective: ")
n1 = input("Enter a noun: ")
n2 = input("Enter another noun: ")
a2 = input("Enter another adjective: ")
a3 = input("Enter another adjective: ")
n3 = input("Enter another noun: ")
num = input("Enter a number: ")
food = input("Enter a Food: ")
verb = input("Enter a verb: ")

PLACE = p.capitalize()
NAME = name.capitalize()
ADJECTIVE1 = a1.lower()
NOUN1 = n1.lower
NOUN2 = n2.lower
ADJECTIVE2 = a2.lower
ADJECTIVE3 = a3.lower()
NOUN3 = n3.lower()
NUMBER = num.lower()
FOOD = food.lower()
VERB = verb.lower()
print(f"I went to the beach in {PLACE} today with {NAME}.")
print(f"We had a {ADJECTIVE1} time.") 
print(f"We first built a {NOUN1} and then we ran around in the {NOUN2} for a little while.")
print(f"The water was a bit {ADJECTIVE2}.")
print(f"The sun was very {ADJECTIVE3} so we made sure to wear a lot of {NOUN3}.")
print(f"We spent {NUMBER} hours there. At the end of the day, ")
print(f"treated ourselves to a NOUN4 and had {FOOD} for dinner.")
print(f"I definitely want to go to the beach again but next time I want to {VERB}.") 